### ISSUE TITLE
Why these naming? <DoubleDounceLoading/> <RotaingPlaneLoading/>

### ISSUE THREAD

**Issue by Knowledge91** [akameco/styled-spinkit#1]
Wouldn't `<DoubleBounce />` like in your example be a better convention?

**Comment by akameco** [comment]
@Knowledge91 Thanks.
I agree:)
I'll rename it.

**Comment by Knowledge91** [comment]
The name is still `<DoubleDounce />`

**Comment by akameco** [comment]
@Knowledge91 Oops! Sorry. fixed.
