### ISSUE TITLE
Components seem to crash my app

### ISSUE THREAD

**Issue by nmaves** [akameco/styled-spinkit#14]
Are there any issues using this with CRA or styled-component 3.x?

I am trying something very simple and it seems to crash my app every time.

```
import {FoldingCube} from 'styled-spinkit'

const Loading = () => {
  return (
    <LoadingArea center>
      <FoldingCube color="blue" size="30"/>
    </LoadingArea>
  )
}

```

The above code sends Chome into a panic and pings my CPU.  Any thoughts?

**Comment by akameco** [comment]
The dependent package has been updated.
Please try again.
