### ISSUE TITLE
Possible bug in configuration

### ISSUE THREAD

**Issue by jrusx** [akameco/styled-spinkit#7]
- version: 0.2.0
- `node` version: 8.9.4
- `npm` (or `yarn`) version: npm 5.6.0

**Do you want to request a *feature* or report a *bug*?:**
Bug

**What is the current behavior?:**
The [getRange](https://github.com/akameco/styled-spinkit/blob/6f2cf3026c9e2b4c08486db15940f03015c47f63/src/util/index.js#L28) function, which is used in FadingCircle, WaveLoading, and Circle, is returning an array containing one element of type `Array Iterator`. It appears that the [addition](https://github.com/akameco/styled-spinkit/commit/a7db8eed1e3e6b8f67a71c950b538e86ddc56e48#diff-ff6e5f22a9c7e66987b19c0199636480L14) of `{loose: true}` option for the babel-preset-env in the rollup config is causing the toConsumableArray function to be removed from the bundled script.

The `getRange` function in `dist/styled-spinkit.es.js` with `{loose: true}`:
```
var getRange = function getRange(n) {
  return [].concat(Array(n).keys());
};
```

The `getRange` function in `dist/styled-spinkit.es.js` without `{loose: true}`:
```
var getRange = function getRange(n) {
  return [].concat(toConsumableArray(Array(n).keys()));
};
```

**What is the expected behavior?:**
The `getRange` function should return an array of n elements with values 0 to n-1.

**Suggested solution:**
I don't know all the ins and outs of bundling and rollup configuration, but here are 2 changes that worked for me:

- Remove the `{loose: true}` key/value pair from babel-preset-env options.
and/or
- Replace `[...Array(n).keys()]` with `Array.from(Array(n).keys())` in the `getRange` function.

**Comment by akameco** [comment]
@jrusx Thank you for your reporting 🙌
I think `Array.from(Array(n).keys())` is better.
Could you PRs?

**Comment by jrusx** [comment]
No problem! Okay, I'll make that change and do the pull request now.
